name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  Build:
    runs-on: ubuntu-latest
    container: dockfool/cake-docker:latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
          submodules: true

      - name: Cache packages
        uses: actions/cache@v2.1.6
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('.config/dotnet-tools.json', '**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Docker login
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Cake build
        run: dotnet tool restore && dotnet cake --verbosity=verbose --publish=true
